### ISSUE TITLE
Session Already Started

### ISSUE THREAD

**Issue by gabejepara** [Kledo-ID/php-oauth2-demo#1]
We tryin adding Kledo as modules in our system (that already have defining/handling own Session), and got these warning message, is this can ignored?

> Warning: session_set_cookie_params(): Cannot change session cookie parameters when session is active in /home/kledo/public_html/modules/kledo/vendor/josantonius/session/src/Session.php on line 73
> 
> Notice: session_start(): A session had already been started - ignoring in /home/kledo/public_html/modules/kledo/vendor/josantonius/session/src/Session.php on line 74

in our system flow, modules is below session handling

**Comment by PanjiNamjaElf** [comment]
This repository is only example how to integrate with kledo
Maybe you can remove this `josantonius/session` on composer and implement it with your own session handler
